dist: xenial
language: python
python:
  - "3.7.2"
install:
  - pip install -r server/requirements.txt
services:
  - mysql

env:
  - TEST_DATABASE_URI=mysql+pymysql://2xWx4j4DQi:I30Nd6QrBu@remotemysql.com:3306/2xWx4j4DQi
script:
  - cd server && pytest